### ISSUE TITLE
Code is not clear on how Ignitibility  is transformed and treated

### ISSUE THREAD

**Issue by dschwilk** [schwilklab/flam-psi#4]
All data transformations, cleaning etc should be in the read data type scripts, right?  It looks like ignition is dealt with in an ad-hoc manner later in analysis.R. But I can;t see why. This seems like AFTER the PCA is run which would be backwards.

Additionally, the analysis seem to work on a small subset of the data and I can't figure out why.

**Comment by Azajmahmud** [comment]
Fixed.
